/**
 * Ops-facing borrower history PDF.
 *
 * AUDIENCE: INTERNAL STAFF — full credit history across ALL loans for a single borrower.
 * Used for: credit reviews, arrears escalation, client meetings, audit trails.
 *
 * CONTENTS:
 *   - Borrower profile with internal risk rating
 *   - All loans (active, closed, written-off) with key metrics
 *   - Delinquency history per loan
 *   - NCR arrears summary (for reporting)
 *   - Collections events
 *   - Open AML / fraud flags
 *
 * Must NOT be shared with the borrower.
 */

import React from 'react';
import { Document, Page, Text, View, renderToBuffer } from '@react-pdf/renderer';
import { shared, COLORS, PdfHeader, PdfFooter, KvRow } from './shared';

export interface OpsBorrowerHistoryData {
  generatedAt:  string;
  generatedBy:  string;
  borrower: {
    id:              string;
    name:            string;
    email:           string;
    phone:           string;
    riskRating:      string;
    blacklistFlag:   boolean;
    bureauScore:     number | null;
    kycStatus:       string;
    memberSince:     string;
  };
  summary: {
    totalLoansCount:       number;
    activeLoansCount:      number;
    totalDisbursedRand:    string;
    totalRepaidRand:       string;
    totalOutstandingRand:  string;
    totalWrittenOffRand:   string;
    everDelinquent:        boolean;
    maxDpdEver:            number;
    currentBucket:         string;
  };
  loans: Array<{
    loanNumber:       string;
    product:          string;
    status:           string;
    principalRand:    string;
    aprPct:           string;
    startDate:        string;
    maturityDate:     string;
    totalRepaidRand:  string;
    outstandingRand:  string;
    dpd:              number;
    bucket:           string;
    riskBand:         string;
    collectionsEvents: Array<{ date: string; action: string; outcome: string }>;
  }>;
  openFlags: Array<{ type: 'AML' | 'FRAUD' | 'BLACKLIST'; detail: string; createdAt: string }>;
}

function OpsBorrowerHistoryPDF({ d }: { d: OpsBorrowerHistoryData }) {
  return (
    <Document title={`Borrower History — ${d.borrower.name}`} author="Capstack (Pty) Ltd">
      <Page size="A4" style={shared.page}>
        <PdfHeader title="Borrower History" subtitle="INTERNAL — NOT FOR BORROWER" generatedAt={d.generatedAt} />

        <View style={shared.dangerBox}>
          <Text style={shared.dangerText}>
            INTERNAL DOCUMENT — Contains credit history, risk ratings, and collections data.
            Not for disclosure to the borrower or any third party without legal authority.
            Generated by: {d.generatedBy} · {d.generatedAt}
          </Text>
        </View>

        {/* Borrower profile */}
        <Text style={shared.sectionTitle}>Borrower Profile</Text>
        <KvRow label="Borrower ID"      value={d.borrower.id} />
        <KvRow label="Name"             value={d.borrower.name} />
        <KvRow label="Email"            value={d.borrower.email} />
        <KvRow label="Phone"            value={d.borrower.phone} />
        <KvRow label="Member since"     value={d.borrower.memberSince} />
        <KvRow label="Internal rating"  value={d.borrower.riskRating || 'N/A'} />
        <KvRow label="Bureau score"     value={d.borrower.bureauScore !== null ? String(d.borrower.bureauScore) : 'Not available'} />
        <KvRow label="KYC status"       value={d.borrower.kycStatus} />
        {d.borrower.blacklistFlag && (
          <View style={[shared.dangerBox, { marginTop: 6 }]}>
            <Text style={shared.dangerText}>⚠ BLACKLIST FLAG ACTIVE</Text>
          </View>
        )}

        {/* Portfolio summary */}
        <Text style={shared.sectionTitle}>Portfolio Summary</Text>
        <KvRow label="Total loans"         value={String(d.summary.totalLoansCount)} />
        <KvRow label="Active loans"        value={String(d.summary.activeLoansCount)} />
        <KvRow label="Total disbursed"     value={`R ${d.summary.totalDisbursedRand}`} />
        <KvRow label="Total repaid"        value={`R ${d.summary.totalRepaidRand}`} />
        <KvRow label="Total outstanding"   value={`R ${d.summary.totalOutstandingRand}`} />
        <KvRow label="Total written off"   value={`R ${d.summary.totalWrittenOffRand}`} />
        <KvRow label="Ever delinquent"     value={d.summary.everDelinquent ? 'Yes' : 'No'} />
        <KvRow label="Max DPD ever"        value={String(d.summary.maxDpdEver)} />
        <KvRow label="Current bucket"      value={d.summary.currentBucket} />

        {/* Loan history */}
        <Text style={shared.sectionTitle}>Loan History</Text>
        <View style={shared.table}>
          <View style={shared.tableHeader}>
            {['Ref', 'Product', 'Status', 'Principal', 'APR', 'DPD', 'Band', 'Outstanding'].map(h => (
              <Text key={h} style={[shared.tableHeaderCell, { flex: h === 'Ref' ? 1.5 : 1 }]}>{h}</Text>
            ))}
          </View>
          {d.loans.map((l, i) => (
            <View key={i} style={[shared.tableRow, i % 2 === 1 ? shared.tableRowAlt : {}]}>
              <Text style={[shared.tableCell, { flex: 1.5, fontSize: 6.5 }]}>{l.loanNumber}</Text>
              <Text style={shared.tableCell}>{l.product}</Text>
              <Text style={shared.tableCell}>{l.status}</Text>
              <Text style={shared.tableCell}>R {l.principalRand}</Text>
              <Text style={shared.tableCell}>{l.aprPct}%</Text>
              <Text style={[shared.tableCell, { color: l.dpd > 30 ? COLORS.danger : l.dpd > 0 ? COLORS.accent : '#059669' }]}>
                {l.dpd}
              </Text>
              <Text style={shared.tableCell}>{l.riskBand}</Text>
              <Text style={shared.tableCell}>R {l.outstandingRand}</Text>
            </View>
          ))}
        </View>

        {/* Collections events per loan */}
        {d.loans.filter(l => l.collectionsEvents.length > 0).map(loan => (
          <View key={loan.loanNumber}>
            <Text style={[shared.sectionTitle, { marginTop: 12 }]}>Collections — {loan.loanNumber}</Text>
            {loan.collectionsEvents.map((e, i) => (
              <View key={i} style={{ flexDirection: 'row', gap: 8, paddingVertical: 2, borderBottomWidth: 0.3, borderBottomColor: COLORS.border }}>
                <Text style={{ fontSize: 7.5, color: COLORS.muted, width: 70 }}>{e.date}</Text>
                <Text style={{ fontSize: 7.5, color: COLORS.text, flex: 1 }}>{e.action}</Text>
                <Text style={{ fontSize: 7.5, color: COLORS.muted, width: 100, textAlign: 'right' }}>{e.outcome}</Text>
              </View>
            ))}
          </View>
        ))}

        {/* Open compliance flags */}
        {d.openFlags.length > 0 && (
          <>
            <Text style={shared.sectionTitle}>Open Compliance Flags</Text>
            {d.openFlags.map((f, i) => (
              <View key={i} style={[shared.dangerBox, { marginBottom: 4 }]}>
                <Text style={shared.dangerText}>
                  [{f.type}] {f.detail}  ·  {f.createdAt}
                </Text>
              </View>
            ))}
          </>
        )}

        <PdfFooter pageText="INTERNAL BORROWER HISTORY — RESTRICTED" />
      </Page>
    </Document>
  );
}

export async function renderOpsBorrowerHistory(d: OpsBorrowerHistoryData): Promise<Buffer> {
  return renderToBuffer(<OpsBorrowerHistoryPDF d={d} />) as Promise<Buffer>;
}
