/**
 * Ops-facing full loan record PDF.
 *
 * AUDIENCE: INTERNAL STAFF (credit officers, underwriters, compliance).
 * Includes everything the borrower PDF omits:
 *   - PD score, risk band, credit decision reasoning
 *   - Policy exceptions and flags
 *   - AML alert summary
 *   - KYC check status per check type
 *   - Collections history and DPD bucket
 *   - Internal notes (from ApplicationEvent log)
 *   - Fraud detection signals
 *   - Bureau score
 *
 * ACCESS CONTROL: This route must require STAFF auth (UNDERWRITER | CREDIT_OFFICER | ADMIN | COMPLIANCE).
 * The borrower must NEVER receive this document.
 */

import React from 'react';
import { Document, Page, Text, View, renderToBuffer } from '@react-pdf/renderer';
import { shared, COLORS, PdfHeader, PdfFooter, KvRow } from './shared';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface OpsLoanRecordData {
  generatedAt:    string;
  generatedBy:    string;  // staff name
  loanNumber:     string;
  borrower: {
    id:            string;
    name:          string;
    email:         string;
    phone:         string;
    riskRating:    string;
    blacklistFlag: boolean;
    bureauScore:   number | null;
  };
  loan: {
    id:            string;
    product:       string;
    status:        string;
    principalRand: string;
    aprPct:        string;
    termDays:      number;
    startDate:     string;
    maturityDate:  string;
    dpd:           number;
    bucket:        string;
  };
  decision: {
    recommendation:  string;
    pdScore:         number;
    riskBand:        string;
    approvedAprBps:  number | null;
    reasonCodes:     string[];
    policyExceptions:string[];
    modelVersion:    string;
    decidedAt:       string;
  } | null;
  ncr: {
    totalCostOfCreditRand:   string;
    annualPercentageRatePct: string;
    initiationFeeRand:       string;
  };
  kycChecks: Array<{ type: string; status: string; provider: string; updatedAt: string }>;
  amlAlerts: Array<{ type: string; severity: string; filedSar: boolean; createdAt: string }>;
  fraudSignals: string[];
  repaymentHistory: Array<{ date: string; amountRand: string; rail: string; status: string }>;
  events: Array<{ type: string; notes: string; actorName: string; createdAt: string }>;
}

// ─── PDF Document ─────────────────────────────────────────────────────────────

function OpsLoanRecordPDF({ d }: { d: OpsLoanRecordData }) {
  const riskColor = { A: '#059669', B: COLORS.secondary, C: COLORS.accent, D: '#EA580C', E: COLORS.danger }[d.decision?.riskBand ?? 'C'] ?? COLORS.muted;

  return (
    <Document title={`Ops Loan Record — ${d.loanNumber}`} author="Capstack (Pty) Ltd">
      <Page size="A4" style={shared.page}>
        <PdfHeader title="Full Loan Record" subtitle="INTERNAL — NOT FOR BORROWER" generatedAt={d.generatedAt} />

        <View style={shared.dangerBox}>
          <Text style={shared.dangerText}>
            INTERNAL DOCUMENT — Contains credit risk scores, PD model output, and compliance flags.
            Must NOT be shared with the borrower or any unauthorised third party.
            Generated by: {d.generatedBy} on {d.generatedAt}
          </Text>
        </View>

        {/* Borrower + Risk Profile */}
        <Text style={shared.sectionTitle}>Borrower Profile</Text>
        <KvRow label="Borrower ID"    value={d.borrower.id} />
        <KvRow label="Name"           value={d.borrower.name} />
        <KvRow label="Email"          value={d.borrower.email} />
        <KvRow label="Internal rating" value={d.borrower.riskRating || 'N/A'} />
        <KvRow label="Bureau score"   value={d.borrower.bureauScore !== null ? String(d.borrower.bureauScore) : 'Not available'} />
        {d.borrower.blacklistFlag && (
          <View style={[shared.dangerBox, { marginTop: 6 }]}>
            <Text style={shared.dangerText}>⚠ BLACKLIST FLAG SET — Manual override required before any disbursement.</Text>
          </View>
        )}

        {/* Loan */}
        <Text style={shared.sectionTitle}>Loan Details</Text>
        <KvRow label="Loan number"  value={d.loanNumber} />
        <KvRow label="Product"      value={d.loan.product} />
        <KvRow label="Status"       value={d.loan.status} />
        <KvRow label="Principal"    value={`R ${d.loan.principalRand}`} />
        <KvRow label="APR"          value={`${d.loan.aprPct}%`} />
        <KvRow label="Start"        value={d.loan.startDate} />
        <KvRow label="Maturity"     value={d.loan.maturityDate} />
        <KvRow label="DPD"          value={String(d.loan.dpd)} />
        <KvRow label="Bucket"       value={d.loan.bucket} />

        {/* Credit Decision */}
        {d.decision && (
          <>
            <Text style={shared.sectionTitle}>Credit Decision</Text>
            <KvRow label="Recommendation" value={d.decision.recommendation} />
            <KvRow label="PD Score"       value={`${(d.decision.pdScore * 100).toFixed(2)}%`} />
            <View style={shared.kvRow}>
              <Text style={shared.kvLabel}>Risk band</Text>
              <Text style={[shared.kvValue, { color: riskColor }]}>{d.decision.riskBand}</Text>
            </View>
            <KvRow label="Model version"  value={d.decision.modelVersion} />
            <KvRow label="Decided at"     value={d.decision.decidedAt} />
            {d.decision.reasonCodes.length > 0 && (
              <KvRow label="Reason codes" value={d.decision.reasonCodes.join(', ')} />
            )}
            {d.decision.policyExceptions.length > 0 && (
              <View style={shared.warningBox}>
                <Text style={shared.warningText}>
                  Policy exceptions granted: {d.decision.policyExceptions.join(', ')}
                </Text>
              </View>
            )}
          </>
        )}

        {/* NCR */}
        <Text style={shared.sectionTitle}>NCR Cost of Credit (s.92)</Text>
        <KvRow label="Total cost of credit" value={`R ${d.ncr.totalCostOfCreditRand}`} />
        <KvRow label="APR"                  value={`${d.ncr.annualPercentageRatePct}%`} />
        <KvRow label="Initiation fee"       value={`R ${d.ncr.initiationFeeRand}`} />

        {/* KYC */}
        {d.kycChecks.length > 0 && (
          <>
            <Text style={shared.sectionTitle}>KYC Checks</Text>
            <View style={shared.table}>
              <View style={shared.tableHeader}>
                {['Check type', 'Status', 'Provider', 'Updated'].map(h => (
                  <Text key={h} style={shared.tableHeaderCell}>{h}</Text>
                ))}
              </View>
              {d.kycChecks.map((k, i) => (
                <View key={i} style={[shared.tableRow, i % 2 === 1 ? shared.tableRowAlt : {}]}>
                  <Text style={shared.tableCell}>{k.type}</Text>
                  <Text style={[shared.tableCell, { color: k.status === 'PASSED' ? '#059669' : k.status === 'FAILED' ? COLORS.danger : COLORS.accent }]}>
                    {k.status}
                  </Text>
                  <Text style={shared.tableCell}>{k.provider}</Text>
                  <Text style={shared.tableCell}>{k.updatedAt}</Text>
                </View>
              ))}
            </View>
          </>
        )}

        {/* AML */}
        {d.amlAlerts.length > 0 && (
          <>
            <Text style={shared.sectionTitle}>AML Alerts</Text>
            {d.amlAlerts.map((a, i) => (
              <View key={i} style={[shared.dangerBox, { marginBottom: 4 }]}>
                <Text style={shared.dangerText}>
                  [{a.severity}] {a.type}  ·  SAR Filed: {a.filedSar ? 'YES' : 'No'}  ·  {a.createdAt}
                </Text>
              </View>
            ))}
          </>
        )}

        {/* Fraud signals */}
        {d.fraudSignals.length > 0 && (
          <>
            <Text style={shared.sectionTitle}>Fraud Detection Signals</Text>
            {d.fraudSignals.map((s, i) => (
              <Text key={i} style={{ fontSize: 7.5, color: COLORS.danger, marginBottom: 2 }}>• {s}</Text>
            ))}
          </>
        )}

        {/* Repayment history */}
        {d.repaymentHistory.length > 0 && (
          <>
            <Text style={shared.sectionTitle}>Repayment History</Text>
            <View style={shared.table}>
              <View style={shared.tableHeader}>
                {['Date', 'Amount', 'Rail', 'Status'].map(h => (
                  <Text key={h} style={shared.tableHeaderCell}>{h}</Text>
                ))}
              </View>
              {d.repaymentHistory.map((r, i) => (
                <View key={i} style={[shared.tableRow, i % 2 === 1 ? shared.tableRowAlt : {}]}>
                  <Text style={shared.tableCell}>{r.date}</Text>
                  <Text style={shared.tableCell}>R {r.amountRand}</Text>
                  <Text style={shared.tableCell}>{r.rail}</Text>
                  <Text style={[shared.tableCell, { color: r.status === 'FAILED' ? COLORS.danger : '#059669' }]}>{r.status}</Text>
                </View>
              ))}
            </View>
          </>
        )}

        {/* Internal events / notes */}
        {d.events.length > 0 && (
          <>
            <Text style={shared.sectionTitle}>Event Log &amp; Internal Notes</Text>
            {d.events.map((e, i) => (
              <View key={i} style={{ borderBottomWidth: 0.3, borderBottomColor: COLORS.border, paddingVertical: 4 }}>
                <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                  <Text style={{ fontSize: 7.5, fontFamily: 'Helvetica-Bold', color: COLORS.primary }}>{e.type}</Text>
                  <Text style={{ fontSize: 7, color: COLORS.muted }}>{e.createdAt} · {e.actorName}</Text>
                </View>
                {e.notes && <Text style={{ fontSize: 7.5, color: COLORS.muted, marginTop: 2 }}>{e.notes}</Text>}
              </View>
            ))}
          </>
        )}

        <PdfFooter loanRef={d.loanNumber} pageText="INTERNAL — RESTRICTED" />
      </Page>
    </Document>
  );
}

export async function renderOpsLoanRecord(d: OpsLoanRecordData): Promise<Buffer> {
  return renderToBuffer(<OpsLoanRecordPDF d={d} />) as Promise<Buffer>;
}
